src/Entity/Candidat.php
<?php

namespace App\Entity;

use App\Repository\CandidatRepository;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=CandidatRepository::class)
 */
class Candidat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postnom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $sexe;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $etat_civil;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nationalite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @Vich\UploadableField(mapping="candidat", fileNameProperty="photo")
     */
    private $photo_file = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $province_origine;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu_naissance;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $langues = [];

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $connaissance_informatique = [];

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $experiences_professionnelles = [];

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $personnes_references = [];

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="json")
     */
    private $etudes_faites = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPostnom(): ?string
    {
        return $this->postnom;
    }

    public function setPostnom(string $postnom): self
    {
        $this->postnom = $postnom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getEtatCivil(): ?string
    {
        return $this->etat_civil;
    }

    public function setEtatCivil(string $etat_civil): self
    {
        $this->etat_civil = $etat_civil;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getProvinceOrigine(): ?string
    {
        return $this->province_origine;
    }

    public function setProvinceOrigine(string $province_origine): self
    {
        $this->province_origine = $province_origine;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(string $lieu_naissance): self
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getLangues(): ?array
    {
        return $this->langues;
    }

    public function setLangues(?array $langues): self
    {
        $this->langues = $langues;

        return $this;
    }

    public function getConnaissanceInformatique(): ?array
    {
        return $this->connaissance_informatique;
    }

    public function setConnaissanceInformatique(?array $connaissance_informatique): self
    {
        $this->connaissance_informatique = $connaissance_informatique;

        return $this;
    }

    public function getExperiencesProfessionnelles(): ?array
    {
        return $this->experiences_professionnelles;
    }

    public function setExperiencesProfessionnelles(?array $experiences_professionnelles): self
    {
        $this->experiences_professionnelles = $experiences_professionnelles;

        return $this;
    }

    public function getPersonnesReferences(): ?array
    {
        return $this->personnes_references;
    }

    public function setPersonnesReferences(array $personnes_references): self
    {
        $this->personnes_references = $personnes_references;

        return $this;
    }

    /**
     * @return null
     * @author bernard-ng <ngandubernard@gmail.com>
     */
    public function getPhotoFile()
    {
        return $this->photo_file;
    }

    /**
     * @param null $photo_file
     * @author bernard-ng <ngandubernard@gmail.com>
     */
    public function setPhotoFile($photo_file): void
    {
        $this->photo_file = $photo_file;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getEtudesFaites(): ?array
    {
        return $this->etudes_faites;
    }

    public function setEtudesFaites(array $etudes_faites): self
    {
        $this->etudes_faites = $etudes_faites;

        return $this;
    }
}

src/Controller/AdminCandidatController.php
<?php

namespace App\Controller;

use App\Entity\Candidat;
use App\Form\CandidatType;
use App\Repository\CandidatRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/candidat')]
class AdminCandidatController extends AbstractController
{
    #[Route('/', name: 'admin_candidat_index', methods: ['GET'])]
    public function index(CandidatRepository $candidatRepository): Response
    {
        return $this->render('admin_candidat/index.html.twig', [
            'candidats' => $candidatRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'admin_candidat_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $candidat = new Candidat();
        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($candidat);
            $entityManager->flush();

            return $this->redirectToRoute('admin_candidat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_candidat/new.html.twig', [
            'candidat' => $candidat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'admin_candidat_show', methods: ['GET'])]
    public function show(Candidat $candidat): Response
    {
        return $this->render('admin_candidat/show.html.twig', [
            'candidat' => $candidat,
        ]);
    }

    #[Route('/{id}/edit', name: 'admin_candidat_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Candidat $candidat): Response
    {
        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_candidat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_candidat/edit.html.twig', [
            'candidat' => $candidat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'admin_candidat_delete', methods: ['POST'])]
    public function delete(Request $request, Candidat $candidat): Response
    {
        if ($this->isCsrfTokenValid('delete'.$candidat->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($candidat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_candidat_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_candidat/_delete_form.html.twig
<form method="post" action="{{ path('admin_candidat_delete', {'id': candidat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_candidat/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_candidat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Candidat{% endblock %}

{% block body %}
    <h1>Edit Candidat</h1>

    {{ include('admin_candidat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('admin_candidat_index') }}">back to list</a>

    {{ include('admin_candidat/_delete_form.html.twig') }}
{% endblock %}

templates/admin_candidat/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid mt-5">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header bg-transparent border-0">
                        <h3 class="mb-0">Candidats</h3>
                    </div>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nom</th>
                                <th>Postnom</th>
                                <th>Prenom</th>
                                <th>Sexe</th>
                                <th>Etat_civil</th>
                                <th>Nationalite</th>
                                <th>Photo</th>
                                <th>Province_origine</th>
                                <th>Lieu_naissance</th>
                                <th>Date_naissance</th>
                                <th>Telephone</th>
                                <th>Langues</th>
                                <th>Connaissance_informatique</th>
                                <th>Experiences_professionnelles</th>
                                <th>Personnes_references</th>
                                <th>Adresse</th>
                                <th>Etudes_faites</th>
                                <th>actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for candidat in candidats %}
                                <tr>
                                    <td>{{ candidat.id }}</td>
                                    <td>{{ candidat.nom }}</td>
                                    <td>{{ candidat.postnom }}</td>
                                    <td>{{ candidat.prenom }}</td>
                                    <td>{{ candidat.sexe }}</td>
                                    <td>{{ candidat.etatCivil }}</td>
                                    <td>{{ candidat.nationalite }}</td>
                                    <td>{{ candidat.photo }}</td>
                                    <td>{{ candidat.provinceOrigine }}</td>
                                    <td>{{ candidat.lieuNaissance }}</td>
                                    <td>{{ candidat.dateNaissance ? candidat.dateNaissance|date('Y-m-d H:i:s') : '' }}</td>
                                    <td>{{ candidat.telephone }}</td>
                                    <td>{{ candidat.langues ? candidat.langues|json_encode : '' }}</td>
                                    <td>{{ candidat.connaissanceInformatique ? candidat.connaissanceInformatique|json_encode : '' }}</td>
                                    <td>{{ candidat.experiencesProfessionnelles ? candidat.experiencesProfessionnelles|json_encode : '' }}</td>
                                    <td>{{ candidat.personnesReferences ? candidat.personnesReferences|json_encode : '' }}</td>
                                    <td>{{ candidat.adresse }}</td>
                                    <td>{{ candidat.etudesFaites ? candidat.etudesFaites|json_encode : '' }}</td>
                                    <td>
                                        <a href="{{ path('admin_candidat_show', {'id': candidat.id}) }}">show</a>
                                        <a href="{{ path('admin_candidat_edit', {'id': candidat.id}) }}">edit</a>
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="19">no records found</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/admin_candidat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Candidat{% endblock %}

{% block body %}
    <h1>Create new Candidat</h1>

    {{ include('admin_candidat/_form.html.twig') }}

    <a href="{{ path('admin_candidat_index') }}">back to list</a>
{% endblock %}

templates/admin_candidat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidat{% endblock %}

{% block body %}
<div class="container-fluid mt-5">
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <table class="table">
                    <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ candidat.id }}</td>
                    </tr>
                    <tr>
                        <th>Nom</th>
                        <td>{{ candidat.nom }}</td>
                    </tr>
                    <tr>
                        <th>Postnom</th>
                        <td>{{ candidat.postnom }}</td>
                    </tr>
                    <tr>
                        <th>Prenom</th>
                        <td>{{ candidat.prenom }}</td>
                    </tr>
                    <tr>
                        <th>Sexe</th>
                        <td>{{ candidat.sexe }}</td>
                    </tr>
                    <tr>
                        <th>Etat_civil</th>
                        <td>{{ candidat.etatCivil }}</td>
                    </tr>
                    <tr>
                        <th>Nationalite</th>
                        <td>{{ candidat.nationalite }}</td>
                    </tr>
                    <tr>
                        <th>Photo</th>
                        <td>{{ candidat.photo }}</td>
                    </tr>
                    <tr>
                        <th>Province_origine</th>
                        <td>{{ candidat.provinceOrigine }}</td>
                    </tr>
                    <tr>
                        <th>Lieu_naissance</th>
                        <td>{{ candidat.lieuNaissance }}</td>
                    </tr>
                    <tr>
                        <th>Date_naissance</th>
                        <td>{{ candidat.dateNaissance ? candidat.dateNaissance|date('Y-m-d H:i:s') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Telephone</th>
                        <td>{{ candidat.telephone }}</td>
                    </tr>
                    <tr>
                        <th>Langues</th>
                        <td>{{ candidat.langues ? candidat.langues|json_encode : '' }}</td>
                    </tr>
                    <tr>
                        <th>Connaissance_informatique</th>
                        <td>{{ candidat.connaissanceInformatique ? candidat.connaissanceInformatique|json_encode : '' }}</td>
                    </tr>
                    <tr>
                        <th>Experiences_professionnelles</th>
                        <td>{{ candidat.experiencesProfessionnelles ? candidat.experiencesProfessionnelles|json_encode : '' }}</td>
                    </tr>
                    <tr>
                        <th>Personnes_references</th>
                        <td>{{ candidat.personnesReferences ? candidat.personnesReferences|json_encode : '' }}</td>
                    </tr>
                    <tr>
                        <th>Adresse</th>
                        <td>{{ candidat.adresse }}</td>
                    </tr>
                    <tr>
                        <th>Etudes_faites</th>
                        <td>{{ candidat.etudesFaites ? candidat.etudesFaites|json_encode : '' }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}